In [7]:
import pandas as pd
import numpy as np

df = pd.read_parquet('../data/fhvhv_tripdata_2025-05.parquet')
zone = pd.read_csv('../data/taxi_zone_lookup.csv') 
vendor = pd.read_csv('../data/taxi_vendor_lookup.csv')
payment = pd.read_csv('../data/payment_lookup.csv')
hvfhs = pd.read_csv('../data/hvfhs_lookup.csv')

In [2]:
df.isna().sum()

hvfhs_license_num             0
dispatching_base_num          0
originating_base_num    6034550
request_datetime              0
on_scene_datetime             0
pickup_datetime               0
dropoff_datetime              0
PULocationID                  0
DOLocationID                  0
trip_miles                    0
trip_time                     0
base_passenger_fare           0
tolls                         0
bcf                           0
sales_tax                     0
congestion_surcharge          0
airport_fee                   0
tips                          0
driver_pay                    0
shared_request_flag           0
shared_match_flag             0
access_a_ride_flag            0
wav_request_flag              0
wav_match_flag                0
cbd_congestion_fee            0
dtype: int64

In [3]:
df.head()

,hvfhs_license_num,dispatching_base_num,originating_base_num,request_datetime,on_scene_datetime,pickup_datetime,dropoff_datetime,PULocationID,DOLocationID,trip_miles,...,congestion_surcharge,airport_fee,tips,driver_pay,shared_request_flag,shared_match_flag,access_a_ride_flag,wav_request_flag,wav_match_flag,cbd_congestion_fee
0,HV0003,B03404,B03404,2025-04-30 23:59:52,2025-05-01 00:03:02,2025-05-01 00:03:25,2025-05-01 00:12:22,160,82,2.51,...,0.00,0.0,0.0,10.47,N,N,N,N,N,0.0
1,HV0003,B03404,B03404,2025-05-01 00:05:01,2025-05-01 00:06:30,2025-05-01 00:07:04,2025-05-01 00:17:17,82,129,1.51,...,0.00,0.0,0.0,8.34,N,N,N,N,N,0.0
2,HV0003,B03404,B03404,2025-05-01 00:16:00,2025-05-01 00:19:06,2025-05-01 00:20:32,2025-05-01 00:39:01,129,226,5.01,...,0.00,0.0,0.0,18.28,N,N,N,N,N,0.0
3,HV0005,B03406,None,2025-05-01 00:44:56,2025-05-01 00:49:38,2025-05-01 00:50:38,2025-05-01 01:00:23,37,112,1.29,...,0.00,0.0,0.0,8.26,N,N,N,N,Y,0.0
4,HV0003,B03404,B03404,2025-05-01 00:04:08,2025-05-01 00:04:39,2025-05-01 00:06:24,2025-05-01 00:31:44,97,87,5.04,...,2.75,0.0,0.0,22.44,N,N,N,N,N,1.5

In [4]:
df['originating_base_num'].unique()

array(['B03404', None, 'B03406', 'B02026', 'B02003'], dtype=object)

In [5]:
# also replace np.nan with NA to standardize
df['originating_base_num'].replace({None: pd.NA}, inplace=True)

In [6]:
#checking for duplicates
df.duplicated().sum()

0